function createData(
  _id,
  id_sede,
  name,
  mail,
  telefono,
  lugar_origen,
  street,
  number,
  postal_code,
  url_video,
  comprobante_pago,
  identificacion_personal,
  nombre_tema,
  experiencia_artistica,
  fecha_nacimiento,
  genero
) {
  return {
    _id,
    id_sede,
    name,
    mail,
    telefono,
    lugar_origen,
    street,
    number,
    postal_code,
    url_video,
    comprobante_pago,
    identificacion_personal,
    nombre_tema,
    experiencia_artistica,
    fecha_nacimiento,
    genero,
  };
}

createData(
  "1",
  "1sdfbh536h",
  "juan",
  "juan@gmail.com",
  "317124235",
  "Jalisco",
  "20 de noviembre",
  "34",
  "48900",
  "url_video",
  "comprobante",
  "ine",
  "soul sacrifice",
  "soy canta-autor desde los 15 años",
  "28 feb 1996",
  "Hombre"
);

export const rows = [createData(
    "1",
    "1sdfbh536h",
    "juan miguel",
    "juan@gmail.com",
    "317124235",
    "Jalisco",
    "20 de noviembre",
    "34",
    "48900",
    "url_video",
    "comprobante",
    "ine",
    "soul sacrifice",
    "soy canta-autor desde los 15 años",
    "24 feb 1994",
    "Hombre"
  ),
  createData(
    "2",
    "1sdask9936h",
    "luis nieto",
    "luis@gmail.com",
    "317124235",
    "Tijuana",
    "Galeana",
    "64",
    "47980",
    "url_video",
    "comprobante",
    "ine",
    "enter sandman",
    "no canto bonito pero tengo sentimiento",
    "17 jun 1990",
    "Hombre"
  ),
  createData(
    "3",
    "946jernfd32",
    "jose perez",
    "joseperez@gmail.com",
    "317124235",
    "Jalisco",
    "hidalgo",
    "654",
    "42300",
    "url_video",
    "comprobante",
    "ine",
    "nothing else matters",
    "soy buen guitarrista, comence desde los 8 a tocar instrumentos",
    "10 nov 2000",
    "Hombre"
  ),
  createData(
    "4",
    "1aaa00536h",
    "maria gonzales",
    "maria@gmail.com",
    "317124235",
    "cdmx",
    "Av mariano otero",
    "2358",
    "46700",
    "url_video",
    "comprobante",
    "ine",
    "wind of change",
    "me gusta la musica y tocar la guitarra",
    "7 Abril 2002",
    "Mujer"
  )
];